[tool.poetry]
name = "caravanassets"
version = "0.1.4"
description = "This is a python package for implementing the card game Caravan"

license = "MIT"

authors = ["Anri Tabuev"]
[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"